apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      secure: false
      username: urlshort
    secureJsonData:
      password: urlshort
    editable: true
